### ISSUE TITLE
[Feature Request] Gradient Background

### ISSUE THREAD

**Issue by sifex** [licatajustin/ninja-ui-syntax#2]
Hey, 

Up to you, but I found the gradient background quite nice. Let me know.

```less

atom-text-editor {
  background: rgb(41,42,68);
  background: linear-gradient(30deg, rgb(33, 35, 53) 0%, rgb(55, 56, 88) 100%);

  .gutter {
    background: transparent;
  }
  .gutter-container {
    background: rgba(0,0,0,0.08);
  }
}

```
